version: "3.9"

services:
  users-service:
    build: ./users_service
    container_name: desafio5-users
    networks:
      - internal-net

  orders-service:
    build: ./orders_service
    container_name: desafio5-orders
    networks:
      - internal-net

  gateway:
    build: ./gateway
    container_name: desafio5-gateway
    depends_on:
      - users-service
      - orders-service
    environment:
      USERS_SERVICE_URL: http://users-service:5000
      ORDERS_SERVICE_URL: http://orders-service:5001
    ports:
      - "8082:8080"
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge

